// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh6HqEI678_nWYzlBrDgJre0O7ep1M7Es',
    appId: '1:982645835704:web:0457e87dc85246fc35b14d',
    messagingSenderId: '982645835704',
    projectId: 'formmahasiswa-5f427',
    authDomain: 'formmahasiswa-5f427.firebaseapp.com',
    storageBucket: 'formmahasiswa-5f427.firebasestorage.app',
    measurementId: 'G-PFPX6VE25E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpoJBDcaL-Jb9aHLMTDWPo0mjhDv66Nyk',
    appId: '1:982645835704:android:dec1682bee65f19135b14d',
    messagingSenderId: '982645835704',
    projectId: 'formmahasiswa-5f427',
    storageBucket: 'formmahasiswa-5f427.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLUy_VLc6mFlcIXY8r73FNx3nyNWPtNiY',
    appId: '1:982645835704:ios:b1478d06213c6c8035b14d',
    messagingSenderId: '982645835704',
    projectId: 'formmahasiswa-5f427',
    storageBucket: 'formmahasiswa-5f427.firebasestorage.app',
    iosBundleId: 'com.example.mynoteku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLUy_VLc6mFlcIXY8r73FNx3nyNWPtNiY',
    appId: '1:982645835704:ios:b1478d06213c6c8035b14d',
    messagingSenderId: '982645835704',
    projectId: 'formmahasiswa-5f427',
    storageBucket: 'formmahasiswa-5f427.firebasestorage.app',
    iosBundleId: 'com.example.mynoteku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh6HqEI678_nWYzlBrDgJre0O7ep1M7Es',
    appId: '1:982645835704:web:3a04963ce6f03bc135b14d',
    messagingSenderId: '982645835704',
    projectId: 'formmahasiswa-5f427',
    authDomain: 'formmahasiswa-5f427.firebaseapp.com',
    storageBucket: 'formmahasiswa-5f427.firebasestorage.app',
    measurementId: 'G-SQJZREM26P',
  );

}